apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 214813472555.dkr.ecr.us-east-1.amazonaws.com/virginia-frontend
  newName: 214813472555.dkr.ecr.us-east-1.amazonaws.com/virginia-frontend
  newTag: 359ff4fe
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
